#[repr(C)]
pub struct ExternProc {
    pub p_un: [u8; 16],
    pub p_vmspace: *mut libc::c_void,
    pub p_sigacts: *mut libc::c_void,
    pub p_flag: i32,
    pub p_stat: u8,
    pub p_pid: i32,
    pub p_oppid: i32,
    pub p_dupfd: i32,
    pub user_stack: *mut libc::c_void,
    pub exit_thread: *mut libc::c_void,
    pub p_debugger: i32,
    pub sigwait: bool,
    pub p_estcpu: u32,
    pub p_cpticks: i32,
    pub p_pctcpu: fixpt_t,
    pub p_wchan: *mut libc::c_void,
    pub p_wmesg: *mut libc::c_char,
    pub p_swtime: u32,
    pub p_slptime: u32,
    pub p_realtimer: libc::itimerval,
    pub p_rtime: libc::timeval,
    pub p_uticks: u64,
    pub p_sticks: u64,
    pub p_iticks: u64,
    pub p_traceflag: i32,
    pub p_tracep: *mut libc::c_void,
    pub p_siglist: i32,
    pub p_textvp: *mut libc::c_void,
    pub p_holdcnt: i32,
    pub p_sigmask: libc::sigset_t,
    pub p_sigignore: libc::sigset_t,
    pub p_sigcatch: libc::sigset_t,
    pub p_priority: u8,
    pub p_usrpri: u8,
    pub p_nice: i16,
    pub p_xstat: u16,
    pub p_acflag: u16,
    pub p_ru: libc::rusage,
}

#[repr(C)]
pub struct Proc {
    pub p_un: [u8; 16],
    pub p_vmspace: *mut libc::c_void,
    pub p_sigacts: *mut libc::c_void,
    pub p_flag: i32,
    pub p_stat: u8,
    pub p_pid: i32,
    pub p_oppid: i32,
    pub p_dupfd: i32,
    pub user_stack: *mut libc::c_void,
    pub exit_thread: *mut libc::c_void,
    pub p_debugger: i32,
    pub sigwait: bool,
    pub p_estcpu: u32,
    pub p_cpticks: i32,
    pub p_pctcpu: fixpt_t,
    pub p_wchan: *mut libc::c_void,
    pub p_wmesg: *mut libc::c_char,
    pub p_swtime: u32,
    pub p_slptime: u32,
    pub p_realtimer: libc::itimerval,
    pub p_rtime: libc::timeval,
    pub p_uticks: u64,
    pub p_sticks: u64,
    pub p_iticks: u64,
    pub p_traceflag: i32,
    pub p_tracep: *mut libc::c_void,
    pub p_siglist: i32,
    pub p_textvp: *mut libc::c_void,
    pub p_holdcnt: i32,
    pub p_sigmask: libc::sigset_t,
    pub p_sigignore: libc::sigset_t,
    pub p_sigcatch: libc::sigset_t,
    pub p_priority: u8,
    pub p_usrpri: u8,
    pub p_nice: i16,
    pub p_xstat: u16,
    pub p_acflag: u16,
    pub p_ru: libc::rusage,
}

#[repr(C)]
pub union fixpt_t {
    pub unsigned_value: u32,
    pub signed_value: i32,
}

#[repr(C)]
pub struct KinfoProc {
    pub kp_proc: Proc,
    pub kp_eproc: ExternProc,
}
